export const documentedCredentials = [
  { email: "analyst@case-study.local", password: "analyst-password", passwordHash: "$2b$12$4.3tX2A7jAC.7GENOiUcZO6cboPwUogCM2lNjUwSWioyfBEhulJii", name: "Avery Analyst", role: "ANALYST" },
  { email: "lead@case-study.local", password: "lead-password", passwordHash: "$2b$12$Yedf7kQJ8JMDAk6prQgxJ.ADPMnsTvSky.FqsGal6CfHNSGcNmZ/O", name: "Emerson Lead", role: "ENGINEERING_LEAD" },
] as const;

export const designVariables = [
  ["EPS-BATTERY-CAPACITY", "Battery capacity", "120.5", "Wh", "EPS", "Usable spacecraft battery energy.", true], ["EPS-SOLAR-ARRAY-POWER", "Solar array power", "185", "W", "EPS", "Beginning-of-life solar array output.", false], ["EPS-BUS-VOLTAGE", "Bus voltage", "28", "V", "EPS", "Nominal regulated spacecraft bus voltage.", true], ["EPS-PEAK-LOAD", "Peak load", "142", "W", "EPS", "Maximum simultaneous electrical load.", false], ["EPS-DEPTH-OF-DISCHARGE", "Depth of discharge", "0.2", "ratio", "EPS", "Maximum allowable battery depth of discharge.", true], ["EPS-POWER-MARGIN", "Power margin", "0.25", "ratio", "EPS", "Required end-of-life power margin.", false], ["EPS-CHARGE-EFFICIENCY", "Charge efficiency", "0.92", "ratio", "EPS", "Battery charge conversion efficiency.", false], ["EPS-ECLIPSE-DURATION", "Eclipse duration", "35", "min", "EPS", "Design maximum eclipse duration.", true],
  ["THERMAL-SURVIVAL-MIN", "Survival temperature minimum", "-20", "C", "Thermal", "Lowest allowable survival temperature.", true], ["THERMAL-SURVIVAL-MAX", "Survival temperature maximum", "55", "C", "Thermal", "Highest allowable survival temperature.", true], ["THERMAL-OPERATING-MIN", "Operating temperature minimum", "-10", "C", "Thermal", "Lowest allowable operating temperature.", false], ["THERMAL-OPERATING-MAX", "Operating temperature maximum", "45", "C", "Thermal", "Highest allowable operating temperature.", false], ["THERMAL-RADIATOR-AREA", "Radiator area", "0.18", "m2", "Thermal", "Effective radiator rejection area.", false], ["THERMAL-COATING-EMISSIVITY", "Coating emissivity", "0.85", "ratio", "Thermal", "External thermal coating emissivity.", false], ["THERMAL-COATING-ABSORPTIVITY", "Coating absorptivity", "0.32", "ratio", "Thermal", "External thermal coating solar absorptivity.", false], ["THERMAL-HEATER-POWER", "Heater power", "28", "W", "Thermal", "Installed survival heater allocation.", true],
  ["STRUCTURES-DRY-MASS", "Dry mass", "18.6", "kg", "Structures", "Spacecraft dry mass allocation.", true], ["STRUCTURES-PAYLOAD-MASS", "Payload mass", "4.2", "kg", "Structures", "Payload mass allocation.", true], ["STRUCTURES-LAUNCH-MASS", "Launch mass", "26", "kg", "Structures", "Total launch mass limit.", true], ["STRUCTURES-FIRST-MODE", "First natural frequency", "65", "Hz", "Structures", "Minimum first structural natural frequency.", true], ["STRUCTURES-FACTOR-OF-SAFETY", "Factor of safety", "1.4", "ratio", "Structures", "Yield factor of safety.", true], ["STRUCTURES-CG-OFFSET", "Center of gravity offset", "12", "mm", "Structures", "Maximum center of gravity offset from axis.", false], ["STRUCTURES-PANEL-THICKNESS", "Panel thickness", "1.5", "mm", "Structures", "Primary panel skin thickness.", false], ["STRUCTURES-FASTENER-TORQUE", "Fastener torque", "2.8", "Nm", "Structures", "Nominal primary fastener torque.", false],
  ["COMM-RF-POWER", "RF transmit power", "5", "W", "Communications", "Nominal RF transmitter output power.", true], ["COMM-DOWNLINK-RATE", "Downlink data rate", "2", "Mbps", "Communications", "Nominal downlink data rate.", false], ["COMM-UPLINK-RATE", "Uplink data rate", "256", "kbps", "Communications", "Nominal uplink data rate.", false], ["COMM-ANTENNA-GAIN", "Antenna gain", "6.5", "dBi", "Communications", "Communications antenna gain.", false], ["COMM-LINK-MARGIN", "Link margin", "3", "dB", "Communications", "Minimum downlink link margin.", true], ["COMM-FREQUENCY", "Operating frequency", "2250", "MHz", "Communications", "Assigned downlink center frequency.", true], ["COMM-PASS-DURATION", "Ground pass duration", "8", "min", "Communications", "Expected median ground-station pass duration.", false], ["COMM-CODING-GAIN", "Coding gain", "4.5", "dB", "Communications", "Forward error correction coding gain.", false],
] as const;
